name: Deploy to AWS EC2 (Vite Project)

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm' 

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          
          SOURCE: "dist/"
          TARGET: ${{ secrets.EC2_TARGET_DIR }} 
          ARGS: '--delete'

      - name: Run post-deploy commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deployment complete. Running post-deploy steps..."
            # --- Add your EC2 server commands below ---
            # Example: Restart Nginx
             sudo systemctl restart nginx
            # Example: If using PM2 for a Node.js server (unlikely for static Vite build)
            # pm2 reload yourappname
            # Example: Set permissions if needed for the web server user
            # sudo chown -R www-data:www-data ${{ secrets.EC2_TARGET_DIR }}
            echo "Post-deploy steps finished."